name: smh_flutter_sdk
description: 腾讯云媒资托管_flutter SDK
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  dio: 4.0.6
  crclib: ^3.0.0
  convert:
  connectivity_plus:
  crypto: ^3.0.1
  intl: 0.17.0
  package_info:
  smh_flutter_beacon_plugin:
    git:
      url: https://github.com/tencentyun/smh_flutter_beacon_plugin.git
